added doux jésus
henrymyers/lorembarnak pull request #20
Opened 2020-10-29 06:57 UTC by pelevesque

2020-10-29 11:09 UTC, henrymyers requested changes

2020-10-29 11:09 UTC, henrymyers commented on lib/index.ts
> +        [`doux jésus`],
Great suggestion! Could you add it to the _jésus_ family though?

2020-10-29 23:33 UTC, henrymyers commented on lib/index.ts
> +        [`doux jésus`],
Also, we now capitalize names 😄

2020-11-01 14:40 UTC, pelevesque commented
It should now be ready to merge.

2020-11-01 21:54 UTC, henrymyers approved these changes
Thanks!

2020-11-01 21:54 UTC, merged